# Generated by Django 4.1.3 on 2023-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passangers',
            name='id',
            field=models.BigAutoField(default=int, auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.BigAutoField(default=int, auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.BigAutoField(default=int, auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
