# Generated by Django 4.1.3 on 2023-01-12 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trains', '0006_remove_passangers_users_passangers_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passangers',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
