# Generated by Django 4.1.3 on 2023-01-12 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trains', '0007_alter_passangers_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passangers',
            name='users',
        ),
        migrations.AddField(
            model_name='passangers',
            name='users',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
