# Generated by Django 4.1.3 on 2023-01-14 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trains', '0009_passangers_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passangers',
            name='users',
        ),
        migrations.AddField(
            model_name='passangers',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
