# Generated by Django 4.1.3 on 2023-01-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0010_remove_passangers_users_passangers_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(default=1),
        ),
    ]
